[package]
name = "polkadot-primitives"
version = "0.6.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", optional = true, features = ["derive"] }
parity-scale-codec = { version = "1.1.0", default-features = false, features = ["bit-vec", "derive"] }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rh-npos-slashing" }
application-crypto = { package = "substrate-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rh-npos-slashing" }
sr-api = { git = "https://github.com/paritytech/substrate", branch = "rh-npos-slashing", default-features = false }
sr-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rh-npos-slashing" }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rh-npos-slashing" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rh-npos-slashing" }
polkadot-parachain = { path = "../parachain", default-features = false }
bitvec = { version = "0.15.2", default-features = false, features = ["alloc"] }
babe = { package = "paint-babe", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rh-npos-slashing" }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/paritytech/substrate", branch = "rh-npos-slashing" }
pretty_assertions = "0.5.1"

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"primitives/std",
	"sr-api/std",
	"rstd/std",
	"sr-version/std",
	"runtime_primitives/std",
	"serde",
	"polkadot-parachain/std",
	"bitvec/std",
	"babe/std"
]
